name: 'dbt_pipeline'
version: '1.0.0'
config-version: 2

# Profile to use for credentials/connection configuration
profile: 'gcp_e2e_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_pipeline:
    # Config for Bronze (Staging) layer - Raw Ingested Native Tables
    bronze:
      +materialized: table
      +schema: bronze_transactions
    # Config for Silver layer - Cleaned/Normalized Native Tables
    silver:
      +materialized: table
      +schema: silver_transactions
    # Config for Gold layer - Aggregated Native Tables and Views for Looker Studio
    gold:
      +materialized: view
      +schema: gold_transactions
