version: 2

sources:
  - name: raw_source
    database: e2e-data-pipeline-497509
    schema: bronze_transactions
    tables:
      - name: transactions_raw
        description: "Raw ingested transactions table loaded by Batch Ingestion Microservice"
