version: 2

sources:
  - name: bronze
    database: e2e-data-pipeline-497509
    schema: bronze_transactions
    tables:
      - name: raw_grocery_transactions
        description: "Raw ingested grocery chain transactions partitioned by ingestion_date"
